apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-ijyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-ijyc
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-ijyc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-ijyc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-ijyc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-utna-tenant/status-quarkus-io/statusquarkusio-ijyc@sha256:bba2edba51a5dec3e2e2c402c020a4e0e2538b2d4e9c7c637ebba4d3521e1cc7
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
